Move Circe instances to companion objects
avast/scala-hashes pull request #21
Opened 2021-06-10 09:24 UTC by sideeffffect

2021-06-10 09:42 UTC, augi requested changes
Unfortunately, we cannot do this 😢 The reason for having these types in a separate file/package is that the dependency on circe is just optional (see [here](https://github.com/avast/scala-hashes/blob/main/build.gradle#L37)).

If we made this change and use it in an application that doesn't have a dependency on circe (we have those) then we ended with `ClassNotFoundException` (or similar).

2021-06-10 09:49 UTC, sideeffffect commented
I've made the instances `lazy val`, so I think this could work :crossed_fingers:

2021-06-10 10:05 UTC, augi commented
Do you please provide real proof of this behavior? 🙏 I wouldn't want to break anything. Thank you for understanding! 🙏

2021-06-10 10:11 UTC, jendakol commented
I don't have the proof but it _should_ work. I even believe we've used it in some other project 🤔 The logic behind is that unless the user has a circe dependency, these values are never needed and thus not initialized (unless called explicitly - but why would anyone...). Once `Decoder` instance is required, the compiler finds this, lazy val is initialized and everything works.  
Still, it's kind of... potentially dangerous. So I won't express my opinion on whether to use this or that, I just wanted to explain.

2021-06-10 10:31 UTC, augi commented
OK, I will try it myself 😄 The core of my doubts is that I'm not sure how exactly `lazy` works. It is clear that the instance is created during the first access, but IMHO there could be a private field of the same type as the lazy, e.g. `Decoder` in our case). And I believe that JVM loads all types of all fields when accessing a class for the first time 🤔

2021-06-10 11:05 UTC, augi approved these changes
OK, I have a project that has `scala-hashes` as the only dependency so it was easy to try it. And it works! 🎉

2021-06-10 19:20 UTC, merged

2021-06-25 09:08 UTC, augi commented
Unfortunately, our `sbt` builds are failing with this:
```
Symbol 'type io.circe.Encoder' is missing from the classpath.
[error] This symbol is required by 'lazy value com.avast.scala.hashes.Sha256.Sha256Encoder'.
[error] Make sure that type Encoder is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'Sha256.class' was compiled against an incompatible version of io.circe.
```
Do you have any idea how to overcome this, please? @sideeffffect